name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  # NOTE: fuzz before tests to catch scanner hanging
  fuzz:
    name: Fuzz parser
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Fuzz parser
      uses: tree-sitter/fuzz-action@v4
      with:
        max-time: 20
        max-length: 1024
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    needs: [fuzz]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Allow long paths
        if: ${{runner.os == 'Windows'}}
        shell: sh
        run: git config --global core.longpaths true
      - name: Clone Quarkus corpus
        uses: actions/checkout@v4
        with:
          path: examples/quarkus
          repository: quarkusio/quarkus
          sparse-checkout-cone-mode: false
          sparse-checkout: |-
            **/*.properties
            !/independent-projects/tools/**
            !/devtools/project-core-extension-codestarts/**
      - name: Clone Spring Boot corpus
        uses: actions/checkout@v4
        with:
          path: examples/spring-boot
          repository: spring-projects/spring-boot
          sparse-checkout-cone-mode: false
          sparse-checkout: "**/*.properties"
      - name: Run parser tests
        uses: tree-sitter/parser-test-action@v2
      - name: Parse sample files
        uses: tree-sitter/parse-action@v4
        id: parse-files
        with:
          files: |-
            examples/quarkus/**/*.properties
            examples/spring-boot/**/*.properties
      - name: Upload failures artifact
        uses: actions/upload-artifact@v4
        if: "!cancelled() && steps.parse-files.outcome == 'failure'"
        with:
          name: failures-${{runner.os}}
          path: ${{steps.parse-files.outputs.failures}}
