name: Test grammar

on:
  push:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    uses: tree-sitter-grammars/.github/.github/workflows/ci.yml@workflows
    with:
      test-library: true
