name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  # NOTE: fuzz before tests to catch scanner hanging
  fuzz:
    name: Fuzz parser
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Fuzz parser
      uses: tree-sitter-grammars/tree-sitter-fuzz-action@v3
      with:
        max-time: 20
        max-length: 1024
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    needs: [fuzz]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Set up repository
        uses: tree-sitter-grammars/actions/setup@main
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Allow long paths
        if: ${{runner.os == 'Windows'}}
        shell: sh
        run: git config --global core.longpaths true
      - name: Clone Quarkus corpus
        uses: actions/checkout@v4
        with:
          path: examples/quarkus
          repository: quarkusio/quarkus
          sparse-checkout-cone-mode: false
          sparse-checkout: |-
            **/*.properties
            !/independent-projects/tools/**
            !/devtools/project-core-extension-codestarts/**
          ref: 8ff8180fd5d629621ee2807b32024520c7693c42
      - name: Clone Spring Boot corpus
        uses: actions/checkout@v4
        with:
          path: examples/spring-boot
          repository: spring-projects/spring-boot
          sparse-checkout-cone-mode: false
          sparse-checkout: "**/*.properties"
      - name: Run tests
        uses: tree-sitter-grammars/actions/test@main
        with:
          test-library: ${{runner.os == 'Linux'}}
          examples: |-
            examples/quarkus/**/*.properties
            examples/spring-boot/**/*.properties
